Import('env')

star = env.Object('star.cpp')
projection = env.Object('projection.cpp')
gl_setup = env.Object('gl_setup.cpp')
events = env.Object('events.cpp')
game = env.Object('game.cpp')

Export('star', 'projection', 'gl_setup', 'events', 'game')
