Import('env')

swarmer = env.Object('swarmer.cpp')
projection = env.Object('projection.cpp')
gl_setup = env.Object('gl_setup.cpp')
events = env.Object('events.cpp')
game = env.Object('game.cpp')

Export('swarmer', 'projection', 'gl_setup', 'events', 'game')
