Import('env')
Import('game')
Import('event_handler')

env.Append(CPPPATH = '#/game')
env.Append(CPPPATH = '.')

# build target
env.Program('engine', ['main.cpp', 'defines.cpp', 'error.cpp', 'timing.cpp'] + event_handler + game)
