env = Environment()

env.ParseConfig('sdl-config --cflags')
env.ParseConfig('sdl-config --libs')
env.ParseConfig('pkg-config --libs --cflags glu')

env.Append(CCFLAGS = ['-g', '-Wall'])

env.Append(LIBS = ['SDL_image', 'dl'])

# build target
env.Program('engine', ['main.cpp', 'defines.cpp', 'error.cpp', 'timing.cpp'])
