Import('env')

env.Append(CCFLAGS = ['-g', '-Wall'])

env.Append(CPPPATH = '#/game')
env.Append(CPPPATH = '.')

# build target
env.Program('engine', ['main.cpp', 'defines.cpp', 'error.cpp', 'timing.cpp', 'game.cpp', 'event_handler.cpp'])
