Import('env')
Import('swarmer', 'projection', 'gl_setup', 'events', 'game')

# build target
env.Program('engine', ['main.cpp', 'defines.cpp', 'error.cpp', 'timing.cpp'] + swarmer + projection + gl_setup + events + game)
